### ISSUE TITLE
Bugs: I can't specify the Unity path.

### ISSUE THREAD

**Issue by waya0125** [kurotu/tiny_vcc#4]
**Describe the bug**
Even if you specify Unity's Path in Tiny VCC on macOS, it will not be reflected.

**To Reproduce**
1. Open tiny_vcc
2. Click Settings
3. UI Element VCC Settings, Unity Editors folder icons click
4. select to Unity 2019.4.31f1
5. Wow! It's not reflected.

**Expected behavior**
Originally, Unity's Path should be reflected in that operation.

**Screenshots**
<img width="1184" alt="Screenshot 2023-10-07 10 16 58" src="https://github.com/kurotu/tiny_vcc/assets/42435123/fb646d4f-6b84-451b-8cc0-d7ce8032d1e8">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 14.0 (23A344)

**Additional context**
There is no particular problem because Unity 2019.4.31f1 is managed using Unity Hub.

**Comment by kurotu** [comment]
v0.6.0 should fix the issue. Thank you for feedback.
