### ISSUE TITLE
Bugs: Unity installation is not done normally.

### ISSUE THREAD

**Issue by waya0125** [kurotu/tiny_vcc#5]
**Describe the bug**
Install is not running properly

**To Reproduce**
Press the install button, that's all.

**Expected behavior**
Probably, but the type of CPU is being asked at the time of installation, so I think it would be good to solve it.

**Screenshots**
It is japanese text. I'm so sorry.
<img width="1010" alt="Screenshot 2023-10-07 10 11 13" src="https://github.com/kurotu/tiny_vcc/assets/42435123/d59b3e9b-fe1b-4faa-82a2-ae4d28e93687">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 14.0 (23A344)

**Comment by kurotu** [comment]
I believe 916d5a65 should fix the issue, but I don't have apple silicon mac.
Would you try [this artifact](https://github.com/kurotu/tiny_vcc/suites/16977278358/artifacts/969940638) of the workflow job?: https://github.com/kurotu/tiny_vcc/actions/runs/6439011224

**Comment by waya0125** [comment]
Got it. I'll check it.

**Comment by waya0125** [comment]
Sorry, but I don't know how to initialize the application settings in a Mac environment. Once Install is done, I need to blow up the settings, but it seems that just erasing the package is not enough. Do you know anything about this?

**Comment by kurotu** [comment]
Sorry for inconvenience, you need to remove existing Unity Editor and reset VCC settings.

1. Quit Tiny VCC.
2. Remove Unity folder: `/Applications/Unity/Hub/Editor/2019.4.31f1`
3. Edit VCC settings: `~/.local/share/VRChatCreatorCompanion/settings.json`
    ```json
    /// Clear pathToUnityExe and unityEditors values. Keep other parameters as is.
    {
      "pathToUnityExe": "",
      "unityEditors": []
    }
    ```

**Comment by kurotu** [comment]
Please let me know if it seems hard to test. I'll release the bugfix as is.

**Comment by waya0125** [comment]
![image](https://github.com/kurotu/tiny_vcc/assets/42435123/dc4580c0-fc65-46bd-b344-209e16a95cc4)
![image](https://github.com/kurotu/tiny_vcc/assets/42435123/75d92155-9df3-4ba9-acac-f89f36494a27)
It's probably not working correctly. It's stopped in the same place as last time.

**Comment by kurotu** [comment]
Sorry again, I forgot to let you know. Please make sure you are using Unity Hub 3.5.1 or later.

**Comment by waya0125** [comment]
I using `Unity Hub 3.5.2`
![image](https://github.com/kurotu/tiny_vcc/assets/42435123/2532b546-3081-4f7c-9252-0401d5df79af)

**Comment by kurotu** [comment]
Thank you for kind feedback. I'll investigate more.

**Comment by waya0125** [comment]
Thanks you.

When I looked it up, I was glaring that this might be the cause because there is a warning message at the beginning that occurs when updating to macOS Sonoma.

**Comment by kurotu** [comment]
I made a new artifact: https://github.com/kurotu/tiny_vcc/suites/17068682673/artifacts/974918616
The problem was architecture detection in tiny vcc's code.

"Secure coding" sentence seems just a warning for Unity Hub on Sonoma. I think it's not related to this issue.

**Comment by waya0125** [comment]
Ok. I'll check it out now.
Sorry for the irrelevant remarks.

**Comment by waya0125** [comment]
OK, working.
![image](https://github.com/kurotu/tiny_vcc/assets/42435123/e580c8a9-6575-48c8-8bf2-0f5b196116cb)

**Comment by waya0125** [comment]
Ahhhh, I was able to install it, but I can't recognize the installed file and it will be an error judgment.
![image](https://github.com/kurotu/tiny_vcc/assets/42435123/3e5cf091-01a2-451b-aec3-9a01e5009994)

**Comment by kurotu** [comment]
Unity Hub CLI's output is different on Apple Silicon, so version detection failed.
Sorry to bother you again, I made a new artifact to fix: https://github.com/kurotu/tiny_vcc/suites/17112075644/artifacts/977497951

 I believe this is the last one because Unity Hub part is all done.

**Comment by waya0125** [comment]
I can now get information from Unity Hub correctly, but it can be written even if it is not Unity 2019.4.31f1, is it okay?
![image](https://github.com/kurotu/tiny_vcc/assets/42435123/8fa60f34-e03b-44d8-ab8e-30b01d781b39)

**Comment by kurotu** [comment]
Thank you for testing. At least now we can get unity installed, so I can inspect further behavior on my Mac.
Would you execute Unity Hub in terminal? I'll check it with #4.

```
/Applications/Unity\ Hub.app/Contents/MacOS/Unity\ Hub -- --headless editors --installed
```

**Comment by waya0125** [comment]
I was late in confirming. My apologies.
I'll try to run it right after this.

**Comment by waya0125** [comment]
![image](https://github.com/kurotu/tiny_vcc/assets/42435123/db3c38ce-e640-4679-98bc-159dbbe7dc70)

**Comment by waya0125** [comment]
Unity that comes at the top is automatically assigned, so if 2019 is not included, the installation should be executed, but it is no longer executed.

**Comment by kurotu** [comment]
I added version check for the issue above. But it originally relies on `vpm check unity`, so the issue may happen. In such case, please manually install appropriate unity.

**Comment by waya0125** [comment]
When I specified it by hand, it started to work.
I'm sorry to trouble you for a long time.

**Comment by kurotu** [comment]
v0.6.0 should fix the issue. Thank you for kind cooperation.
