### ISSUE TITLE
Unable to Create Avatar Project (M1 Macbook Pro)

### ISSUE THREAD

**Issue by nargleflex** [kurotu/tiny_vcc#6]
**Describe the bug**
Can't launch a newly created avatar project

**To Reproduce**

(executing on an M1 Macbook Pro)
1. Made sure the right version of unity is installed and executes
2. Installed Tiny VCC and selected the unity editor from above
3. Created a new project from the avatar template
4. When selecting the new project, I get the following error:
```/Users/nargle/Unity Test is invalid project.```

**Expected behavior**
Expected unity to launch with the newly created project

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 13.5.1 (22G90) - Ventura

**Comment by kurotu** [comment]
Sadly not reproduced.
The project type is identified by `vpm check project` command. Would you check following points?
- Output of `vpm check project "/Users/nargle/Unity Test"` in Terminal.cpp
- You can open the project with Unity Hub.

**Comment by kurotu** [comment]
Closed for archiving.
