### ISSUE TITLE
Unity 2019 Required

### ISSUE THREAD

**Issue by Dog** [kurotu/tiny_vcc#9]
On a fresh install, a project cannot be created on Mac without Unity 2019.

I installed Unity 2022, Installed Android and Windows build support for it, CPM CLI, and .NET6.0 SDK.

However the last step will not complete as it seems to assume Unity 2019 must be installed.
This seems to need to be updated since VRChat now supports Unity 2022.

Additionally attempting to continue and hit "Install", the application attempts to install Unity 2019 despite the 2022 SDK template being selected.

**Comment by Dog** [comment]
I was able to get around this issue by adding a personal license in unity hub.

I still get a warning that I have not met the requirements in tinyvcc, but the project will successfully open.

It seems I have to attempt to create a project twice. First one fails telling me Unity is not installed. The second will create the project.

Open project then only sometimes works. I think this is somehow related to if another instance of Unity is already open outside of tiny-vcc but I'm not really sure.

Regardless, you can manually add the project into Unity Hub and start working. However any additional packages from VPM do not seem to properly add to the project.

**Comment by Dog** [comment]
I was able to get the additional packages to install after a fresh creation after Unity has its first reboot. The first load seemed to only have VRCSDK, but after reload it recognized it needed to fetch the additional packages I added before the first open.

**Comment by kurotu** [comment]
Closed for archiving.
